[book]
title = "一本不成器的笔记罢了"
authors = ["Aaron Taner"]
language = "en"
multilingual = false
src = "src"
description = "一本不成器的笔记罢了"

[output.html]
cname = "keynote.mapkts.com"
google-analytics = "UA-113141331-1"
git-repository-url = "https://github.com/mapkts/keynote"
default-theme = "rust"
mathjax-support = true

[output.html.print]
enable = true

[output.html.fold]
enable = false
level = 0

[output.html.playground]
editable = true
copy-js = true
line-numbers = false
